-- =====================================================================
-- 143 — M-4: RETENSJONSREGISTERET NAVNGIR ALLE MODULENES LAGRE
-- =====================================================================
--
-- M-30 nekter en personvernsak som navngir et lager som ikke staar i
-- registeret — riktig dom («en sak kan bare dekke lagre noen har
-- navngitt og felt en dom over»). Men bare plattformen og seks moduler
-- (M-8, M-28, M-29, M-32, M-40, rekruttering) hadde registrert lagrene
-- sine; en innsynsbegjaering paa disponit.com kunne ikke peke paa
-- loenn, medarbeider, kundeservice, kampanje eller faktura (#424).
--
-- Denne migrasjonen navngir 198 tenant-tabeller fra migrasjonene
-- 094–136 med klasse, tenant- og alderskolonne, og dommen
-- `uten_frist_apen`: fristen er IKKE bestemt her. Det er en aapen dom
-- og ikke et fravaer (093s egen sondring) — hver modul eier fristen
-- sin, og den settes naar den er avgjort. Klassen er lest av
-- kolonnene: `persondata` der raden baerer opplysninger om et
-- menneske, `konfigurasjon` der andre rader refererer den, ellers
-- `driftsspor`. Ingen reaper, ingen frist: 093s CHECK krever begge
-- for `under_frist`, og ingen av dem er husets aa dikte opp.
--
-- Hoppet over (11 tabeller uten tidskolonne — barnerader som
-- foelger forelderen): malkomponent, malfelt, pliktvarsling, lisensvarsling, onboardingmalsteg, purretrinn, ehffelt, ehfavvik, prognosebane, bemanningsbane, rangeringspost.
--
-- Som eierrollen, slik 137–140 gjorde.
-- ---------------------------------------------------------------------
SET LOCAL ROLE disponit_lager_eier;
INSERT INTO retensjonslager
    (lager_id, relasjon, klasse, tenantkolonne, alderskolonne,
     reapetkolonne, fristkilde, frist_dogn, reaper, dom,
     dom_begrunnelse, dom_migrasjon)
VALUES
    ('m5_malfamilie', 'malfamilie', 'konfigurasjon', 'tenant', 'opprettet',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Konfigurasjon som andre rader i modulen refererer til; kan ikke slettes uavhengig av dem. Fristen er aapen i v1 (#424).', '143'),
    ('m5_malversjon', 'malversjon', 'persondata', 'tenant', 'opprettet',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Lageret baerer opplysninger om mennesker (publisert_av). Fristen er ikke bestemt i v1 — den foelger modulens egne regler der de finnes, og er ellers aapen. Navngitt her saa M-30 kan dekke det og M-4 kan maale det (#424).', '143'),
    ('m9_begrep', 'begrep', 'driftsspor', 'tenant', 'opprettet',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m9_begrepsfunn', 'begrepsfunn', 'driftsspor', 'tenant', 'forst_sett',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m21_plikt', 'plikt', 'persondata', 'tenant', 'opprettet',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Lageret baerer opplysninger om mennesker (eier_bruker_id). Fristen er ikke bestemt i v1 — den foelger modulens egne regler der de finnes, og er ellers aapen. Navngitt her saa M-30 kan dekke det og M-4 kan maale det (#424).', '143'),
    ('m21_pliktvarsel_sendt', 'pliktvarsel_sendt', 'driftsspor', 'tenant', 'frist_ts',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m12_tilgangsobjekt', 'tilgangsobjekt', 'driftsspor', 'tenant', 'opprettet',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m12_tilgang', 'tilgang', 'persondata', 'tenant', 'opprettet',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Lageret baerer opplysninger om mennesker (eier_bruker_id). Fristen er ikke bestemt i v1 — den foelger modulens egne regler der de finnes, og er ellers aapen. Navngitt her saa M-30 kan dekke det og M-4 kan maale det (#424).', '143'),
    ('m12_tilgangsfunn', 'tilgangsfunn', 'driftsspor', 'tenant', 'forst_sett',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m22_lisens', 'lisens', 'persondata', 'tenant', 'opprettet',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Lageret baerer opplysninger om mennesker (eier_bruker_id). Fristen er ikke bestemt i v1 — den foelger modulens egne regler der de finnes, og er ellers aapen. Navngitt her saa M-30 kan dekke det og M-4 kan maale det (#424).', '143'),
    ('m22_lisensvarsel_sendt', 'lisensvarsel_sendt', 'driftsspor', 'tenant', 'koet_ts',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m30_personvernsak', 'personvernsak', 'persondata', 'tenant', 'opprettet',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Lageret baerer opplysninger om mennesker (eier_bruker_id, subjekt_ref). Fristen er ikke bestemt i v1 — den foelger modulens egne regler der de finnes, og er ellers aapen. Navngitt her saa M-30 kan dekke det og M-4 kan maale det (#424).', '143'),
    ('m30_personvernsak_lager', 'personvernsak_lager', 'driftsspor', 'tenant', 'lagt_til',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m30_personvernfunn', 'personvernfunn', 'driftsspor', 'tenant', 'forst_sett',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m34_rammeverk', 'rammeverk', 'driftsspor', 'tenant', 'opprettet',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m34_kontroll', 'kontroll', 'persondata', 'tenant', 'opprettet',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Lageret baerer opplysninger om mennesker (eier_bruker_id). Fristen er ikke bestemt i v1 — den foelger modulens egne regler der de finnes, og er ellers aapen. Navngitt her saa M-30 kan dekke det og M-4 kan maale det (#424).', '143'),
    ('m34_etterproving', 'etterproving', 'driftsspor', 'tenant', 'opprettet',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m34_kontrollfunn', 'kontrollfunn', 'driftsspor', 'tenant', 'forst_sett',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m13_bankkonto', 'bankkonto', 'driftsspor', 'tenant', 'opprettet',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m13_bankpost', 'bankpost', 'persondata', 'tenant', 'opprettet',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Lageret baerer opplysninger om mennesker (motpart). Fristen er ikke bestemt i v1 — den foelger modulens egne regler der de finnes, og er ellers aapen. Navngitt her saa M-30 kan dekke det og M-4 kan maale det (#424).', '143'),
    ('m13_bilag', 'bilag', 'persondata', 'tenant', 'opprettet',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Lageret baerer opplysninger om mennesker (motpart). Fristen er ikke bestemt i v1 — den foelger modulens egne regler der de finnes, og er ellers aapen. Navngitt her saa M-30 kan dekke det og M-4 kan maale det (#424).', '143'),
    ('m13_avstemming', 'avstemming', 'driftsspor', 'tenant', 'opprettet',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m13_avstemmingsfunn', 'avstemmingsfunn', 'driftsspor', 'tenant', 'forst_sett',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m17_henvendelse', 'henvendelse', 'persondata', 'tenant', 'mottatt',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Lageret baerer opplysninger om mennesker (avsender_hash). Fristen er ikke bestemt i v1 — den foelger modulens egne regler der de finnes, og er ellers aapen. Navngitt her saa M-30 kan dekke det og M-4 kan maale det (#424).', '143'),
    ('m17_klassifisering', 'klassifisering', 'driftsspor', 'tenant', 'opprettet',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m17_svarutkast', 'svarutkast', 'driftsspor', 'tenant', 'opprettet',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m17_henvendelsesfunn', 'henvendelsesfunn', 'driftsspor', 'tenant', 'forst_sett',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m18_onboardingmal', 'onboardingmal', 'konfigurasjon', 'tenant', 'opprettet',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Konfigurasjon som andre rader i modulen refererer til; kan ikke slettes uavhengig av dem. Fristen er aapen i v1 (#424).', '143'),
    ('m18_onboardinglop', 'onboardinglop', 'persondata', 'tenant', 'opprettet',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Lageret baerer opplysninger om mennesker (eier_bruker_id). Fristen er ikke bestemt i v1 — den foelger modulens egne regler der de finnes, og er ellers aapen. Navngitt her saa M-30 kan dekke det og M-4 kan maale det (#424).', '143'),
    ('m18_lopsteg', 'lopsteg', 'persondata', 'tenant', 'fullfort_ts',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Lageret baerer opplysninger om mennesker (eier_bruker_id). Fristen er ikke bestemt i v1 — den foelger modulens egne regler der de finnes, og er ellers aapen. Navngitt her saa M-30 kan dekke det og M-4 kan maale det (#424).', '143'),
    ('m18_onboardingfunn', 'onboardingfunn', 'driftsspor', 'tenant', 'forst_sett',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m23_purreplan', 'purreplan', 'konfigurasjon', 'tenant', 'oppdatert',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Konfigurasjon som andre rader i modulen refererer til; kan ikke slettes uavhengig av dem. Fristen er aapen i v1 (#424).', '143'),
    ('m23_fordring', 'fordring', 'driftsspor', 'tenant', 'opprettet',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m23_fordringshendelse', 'fordringshendelse', 'driftsspor', 'tenant', 'opprettet',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m23_fordringsfunn', 'fordringsfunn', 'driftsspor', 'tenant', 'forst_sett',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m24_leverandorterskel', 'leverandorterskel', 'konfigurasjon', 'tenant', 'oppdatert',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Konfigurasjon som andre rader i modulen refererer til; kan ikke slettes uavhengig av dem. Fristen er aapen i v1 (#424).', '143'),
    ('m24_leverandorpart', 'leverandorpart', 'driftsspor', 'tenant', 'opprettet',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m24_leveranseavtale', 'leveranseavtale', 'driftsspor', 'tenant', 'opprettet',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m24_leveranse', 'leveranse', 'driftsspor', 'tenant', 'registrert',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m24_leverandorfunn', 'leverandorfunn', 'driftsspor', 'tenant', 'forst_sett',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m14_mvasats', 'mvasats', 'driftsspor', 'tenant', 'opprettet',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m14_fakturaterskel', 'fakturaterskel', 'konfigurasjon', 'tenant', 'oppdatert',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Konfigurasjon som andre rader i modulen refererer til; kan ikke slettes uavhengig av dem. Fristen er aapen i v1 (#424).', '143'),
    ('m14_inngaaende_faktura', 'inngaaende_faktura', 'driftsspor', 'tenant', 'opprettet',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m14_fakturakontroll', 'fakturakontroll', 'driftsspor', 'tenant', 'kjort',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m14_fakturafunn', 'fakturafunn', 'driftsspor', 'tenant', 'forst_sett',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m25_prosjektterskel', 'prosjektterskel', 'konfigurasjon', 'tenant', 'oppdatert',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Konfigurasjon som andre rader i modulen refererer til; kan ikke slettes uavhengig av dem. Fristen er aapen i v1 (#424).', '143'),
    ('m25_prosjekt', 'prosjekt', 'driftsspor', 'tenant', 'opprettet',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m25_milepael', 'milepael', 'driftsspor', 'tenant', 'opprettet',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m25_prosjektarbeid', 'prosjektarbeid', 'driftsspor', 'tenant', 'registrert',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m25_prosjektfunn', 'prosjektfunn', 'driftsspor', 'tenant', 'forst_sett',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m26_prisbokterskel', 'prisbokterskel', 'konfigurasjon', 'tenant', 'oppdatert',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Konfigurasjon som andre rader i modulen refererer til; kan ikke slettes uavhengig av dem. Fristen er aapen i v1 (#424).', '143'),
    ('m26_produkt', 'produkt', 'konfigurasjon', 'tenant', 'opprettet',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Konfigurasjon som andre rader i modulen refererer til; kan ikke slettes uavhengig av dem. Fristen er aapen i v1 (#424).', '143'),
    ('m26_pris', 'pris', 'driftsspor', 'tenant', 'opprettet',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m26_klausul', 'klausul', 'konfigurasjon', 'tenant', 'opprettet',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Konfigurasjon som andre rader i modulen refererer til; kan ikke slettes uavhengig av dem. Fristen er aapen i v1 (#424).', '143'),
    ('m26_prisbokfunn', 'prisbokfunn', 'driftsspor', 'tenant', 'forst_sett',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m27_lagerterskel', 'lagerterskel', 'konfigurasjon', 'tenant', 'oppdatert',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Konfigurasjon som andre rader i modulen refererer til; kan ikke slettes uavhengig av dem. Fristen er aapen i v1 (#424).', '143'),
    ('m27_vare', 'vare', 'konfigurasjon', 'tenant', 'opprettet',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Konfigurasjon som andre rader i modulen refererer til; kan ikke slettes uavhengig av dem. Fristen er aapen i v1 (#424).', '143'),
    ('m27_bestillingspunkt', 'bestillingspunkt', 'konfigurasjon', 'tenant', 'opprettet',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Konfigurasjon som andre rader i modulen refererer til; kan ikke slettes uavhengig av dem. Fristen er aapen i v1 (#424).', '143'),
    ('m27_lagerbevegelse', 'lagerbevegelse', 'driftsspor', 'tenant', 'registrert',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m27_lagerfunn', 'lagerfunn', 'driftsspor', 'tenant', 'forst_sett',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m42_kontoterskel', 'kontoterskel', 'konfigurasjon', 'tenant', 'oppdatert',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Konfigurasjon som andre rader i modulen refererer til; kan ikke slettes uavhengig av dem. Fristen er aapen i v1 (#424).', '143'),
    ('m42_betalingsmottaker', 'betalingsmottaker', 'persondata', 'tenant', 'opprettet',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Lageret baerer opplysninger om mennesker (navn). Fristen er ikke bestemt i v1 — den foelger modulens egne regler der de finnes, og er ellers aapen. Navngitt her saa M-30 kan dekke det og M-4 kan maale det (#424).', '143'),
    ('m42_kontooppgave', 'kontooppgave', 'persondata', 'tenant', 'registrert',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Lageret baerer opplysninger om mennesker (oppgitt_av). Fristen er ikke bestemt i v1 — den foelger modulens egne regler der de finnes, og er ellers aapen. Navngitt her saa M-30 kan dekke det og M-4 kan maale det (#424).', '143'),
    ('m42_kontoverifikasjon', 'kontoverifikasjon', 'persondata', 'tenant', 'registrert',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Lageret baerer opplysninger om mennesker (verifisert_av). Fristen er ikke bestemt i v1 — den foelger modulens egne regler der de finnes, og er ellers aapen. Navngitt her saa M-30 kan dekke det og M-4 kan maale det (#424).', '143'),
    ('m42_kontofunn', 'kontofunn', 'driftsspor', 'tenant', 'forst_sett',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m41_betalingsterskel', 'betalingsterskel', 'konfigurasjon', 'tenant', 'oppdatert',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Konfigurasjon som andre rader i modulen refererer til; kan ikke slettes uavhengig av dem. Fristen er aapen i v1 (#424).', '143'),
    ('m41_betalingssubjekt', 'betalingssubjekt', 'persondata', 'tenant', 'opprettet',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Lageret baerer opplysninger om mennesker (navn). Fristen er ikke bestemt i v1 — den foelger modulens egne regler der de finnes, og er ellers aapen. Navngitt her saa M-30 kan dekke det og M-4 kan maale det (#424).', '143'),
    ('m41_betalingshendelse', 'betalingshendelse', 'driftsspor', 'tenant', 'registrert',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m41_abonnementsperiode', 'abonnementsperiode', 'driftsspor', 'tenant', 'opprettet',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m41_betalingsfunn', 'betalingsfunn', 'driftsspor', 'tenant', 'forst_sett',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m19_adressekrav', 'adressekrav', 'konfigurasjon', 'tenant', 'oppdatert',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Konfigurasjon som andre rader i modulen refererer til; kan ikke slettes uavhengig av dem. Fristen er aapen i v1 (#424).', '143'),
    ('m19_adressesubjekt', 'adressesubjekt', 'persondata', 'tenant', 'opprettet',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Lageret baerer opplysninger om mennesker (navn). Fristen er ikke bestemt i v1 — den foelger modulens egne regler der de finnes, og er ellers aapen. Navngitt her saa M-30 kan dekke det og M-4 kan maale det (#424).', '143'),
    ('m19_adresseversjon', 'adresseversjon', 'driftsspor', 'tenant', 'registrert',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m19_adressekontroll', 'adressekontroll', 'persondata', 'tenant', 'registrert',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Lageret baerer opplysninger om mennesker (kontrollor). Fristen er ikke bestemt i v1 — den foelger modulens egne regler der de finnes, og er ellers aapen. Navngitt her saa M-30 kan dekke det og M-4 kan maale det (#424).', '143'),
    ('m19_adressefunn', 'adressefunn', 'driftsspor', 'tenant', 'forst_sett',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m39_lonnsterskel', 'lonnsterskel', 'konfigurasjon', 'tenant', 'oppdatert',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Konfigurasjon som andre rader i modulen refererer til; kan ikke slettes uavhengig av dem. Fristen er aapen i v1 (#424).', '143'),
    ('m39_lonnstaker', 'lonnstaker', 'persondata', 'tenant', 'opprettet',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Lageret baerer opplysninger om mennesker (navn). Fristen er ikke bestemt i v1 — den foelger modulens egne regler der de finnes, og er ellers aapen. Navngitt her saa M-30 kan dekke det og M-4 kan maale det (#424).', '143'),
    ('m39_arbeidsplan', 'arbeidsplan', 'driftsspor', 'tenant', 'opprettet',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m39_timeregistrering', 'timeregistrering', 'driftsspor', 'tenant', 'registrert',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m39_lonnsfunn', 'lonnsfunn', 'driftsspor', 'tenant', 'forst_sett',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m44_kampanjegrense', 'kampanjegrense', 'konfigurasjon', 'tenant', 'oppdatert',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Konfigurasjon som andre rader i modulen refererer til; kan ikke slettes uavhengig av dem. Fristen er aapen i v1 (#424).', '143'),
    ('m44_kampanjemottaker', 'kampanjemottaker', 'persondata', 'tenant', 'opprettet',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Lageret baerer opplysninger om mennesker (kontakt_hash). Fristen er ikke bestemt i v1 — den foelger modulens egne regler der de finnes, og er ellers aapen. Navngitt her saa M-30 kan dekke det og M-4 kan maale det (#424).', '143'),
    ('m44_samtykkehendelse', 'samtykkehendelse', 'driftsspor', 'tenant', 'registrert',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m44_kampanje', 'kampanje', 'driftsspor', 'tenant', 'opprettet',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m44_kampanjeplan', 'kampanjeplan', 'driftsspor', 'tenant', 'lagt_til',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m44_kampanjefunn', 'kampanjefunn', 'driftsspor', 'tenant', 'forst_sett',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m48_motpartskrav', 'motpartskrav', 'konfigurasjon', 'tenant', 'oppdatert',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Konfigurasjon som andre rader i modulen refererer til; kan ikke slettes uavhengig av dem. Fristen er aapen i v1 (#424).', '143'),
    ('m48_motpartssubjekt', 'motpartssubjekt', 'persondata', 'tenant', 'opprettet',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Lageret baerer opplysninger om mennesker (navn_oppgitt). Fristen er ikke bestemt i v1 — den foelger modulens egne regler der de finnes, og er ellers aapen. Navngitt her saa M-30 kan dekke det og M-4 kan maale det (#424).', '143'),
    ('m48_foretaksoppslag', 'foretaksoppslag', 'driftsspor', 'tenant', 'reservert',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m48_motpartsversjon', 'motpartsversjon', 'driftsspor', 'tenant', 'registrert',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m48_motpartsvurdering', 'motpartsvurdering', 'driftsspor', 'tenant', 'vurdert',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m48_motpartsfunn', 'motpartsfunn', 'driftsspor', 'tenant', 'forst_sett',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m49_sanksjonskrav', 'sanksjonskrav', 'konfigurasjon', 'tenant', 'oppdatert',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Konfigurasjon som andre rader i modulen refererer til; kan ikke slettes uavhengig av dem. Fristen er aapen i v1 (#424).', '143'),
    ('m49_sanksjonsliste', 'sanksjonsliste', 'konfigurasjon', 'tenant', 'registrert',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Konfigurasjon som andre rader i modulen refererer til; kan ikke slettes uavhengig av dem. Fristen er aapen i v1 (#424).', '143'),
    ('m49_sanksjonssubjekt', 'sanksjonssubjekt', 'persondata', 'tenant', 'opprettet',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Lageret baerer opplysninger om mennesker (fodselsdato, identifikator). Fristen er ikke bestemt i v1 — den foelger modulens egne regler der de finnes, og er ellers aapen. Navngitt her saa M-30 kan dekke det og M-4 kan maale det (#424).', '143'),
    ('m49_sanksjonskontroll', 'sanksjonskontroll', 'driftsspor', 'tenant', 'kontrollert',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m49_sanksjonstreff', 'sanksjonstreff', 'driftsspor', 'tenant', 'registrert',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m49_sanksjonsavklaring', 'sanksjonsavklaring', 'driftsspor', 'tenant', 'avklart',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m49_sanksjonsfunn', 'sanksjonsfunn', 'driftsspor', 'tenant', 'forst_sett',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m46_anbudsprofil', 'anbudsprofil', 'konfigurasjon', 'tenant', 'oppdatert',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Konfigurasjon som andre rader i modulen refererer til; kan ikke slettes uavhengig av dem. Fristen er aapen i v1 (#424).', '143'),
    ('m46_anbud', 'anbud', 'driftsspor', 'tenant', 'registrert',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m46_kvalifikasjonskrav', 'kvalifikasjonskrav', 'konfigurasjon', 'tenant', 'registrert',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Konfigurasjon som andre rader i modulen refererer til; kan ikke slettes uavhengig av dem. Fristen er aapen i v1 (#424).', '143'),
    ('m46_kildedokument', 'kildedokument', 'driftsspor', 'tenant', 'registrert',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m46_anbudsutkast', 'anbudsutkast', 'driftsspor', 'tenant', 'opprettet',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m46_utkastpunkt', 'utkastpunkt', 'driftsspor', 'tenant', 'registrert',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m46_anbudsfunn', 'anbudsfunn', 'driftsspor', 'tenant', 'forst_sett',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m51_tilskuddskrav', 'tilskuddskrav', 'konfigurasjon', 'tenant', 'oppdatert',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Konfigurasjon som andre rader i modulen refererer til; kan ikke slettes uavhengig av dem. Fristen er aapen i v1 (#424).', '143'),
    ('m51_stotteordning', 'stotteordning', 'konfigurasjon', 'tenant', 'registrert',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Konfigurasjon som andre rader i modulen refererer til; kan ikke slettes uavhengig av dem. Fristen er aapen i v1 (#424).', '143'),
    ('m51_kildepost', 'kildepost', 'driftsspor', 'tenant', 'registrert',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m51_tilskuddsestimat', 'tilskuddsestimat', 'driftsspor', 'tenant', 'opprettet',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m51_estimatpost', 'estimatpost', 'driftsspor', 'tenant', 'registrert',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m51_estimatforutsetning', 'estimatforutsetning', 'driftsspor', 'tenant', 'registrert',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m51_tilskuddsfunn', 'tilskuddsfunn', 'driftsspor', 'tenant', 'forst_sett',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m55_merkevarekrav', 'merkevarekrav', 'konfigurasjon', 'tenant', 'oppdatert',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Konfigurasjon som andre rader i modulen refererer til; kan ikke slettes uavhengig av dem. Fristen er aapen i v1 (#424).', '143'),
    ('m55_merkevare', 'merkevare', 'driftsspor', 'tenant', 'registrert',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m55_bevaringskopi', 'bevaringskopi', 'driftsspor', 'tenant', 'registrert',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m55_merkevarefunn', 'merkevarefunn', 'persondata', 'tenant', 'registrert',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Lageret baerer opplysninger om mennesker (motpart). Fristen er ikke bestemt i v1 — den foelger modulens egne regler der de finnes, og er ellers aapen. Navngitt her saa M-30 kan dekke det og M-4 kan maale det (#424).', '143'),
    ('m55_forvekslingsvurdering', 'forvekslingsvurdering', 'driftsspor', 'tenant', 'vurdert',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m55_merkevarevarsel', 'merkevarevarsel', 'driftsspor', 'tenant', 'forst_sett',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m54_ehfkrav', 'ehfkrav', 'konfigurasjon', 'tenant', 'oppdatert',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Konfigurasjon som andre rader i modulen refererer til; kan ikke slettes uavhengig av dem. Fristen er aapen i v1 (#424).', '143'),
    ('m54_ehfregelsett', 'ehfregelsett', 'konfigurasjon', 'tenant', 'registrert',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Konfigurasjon som andre rader i modulen refererer til; kan ikke slettes uavhengig av dem. Fristen er aapen i v1 (#424).', '143'),
    ('m54_ehfregel', 'ehfregel', 'konfigurasjon', 'tenant', 'registrert',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Konfigurasjon som andre rader i modulen refererer til; kan ikke slettes uavhengig av dem. Fristen er aapen i v1 (#424).', '143'),
    ('m54_ehfdokument', 'ehfdokument', 'persondata', 'tenant', 'registrert',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Lageret baerer opplysninger om mennesker (motpart). Fristen er ikke bestemt i v1 — den foelger modulens egne regler der de finnes, og er ellers aapen. Navngitt her saa M-30 kan dekke det og M-4 kan maale det (#424).', '143'),
    ('m54_ehfvalidering', 'ehfvalidering', 'driftsspor', 'tenant', 'validert',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m54_ehfretting', 'ehfretting', 'driftsspor', 'tenant', 'registrert',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m54_ehffunn', 'ehffunn', 'driftsspor', 'tenant', 'forst_sett',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m52_tollkrav', 'tollkrav', 'konfigurasjon', 'tenant', 'oppdatert',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Konfigurasjon som andre rader i modulen refererer til; kan ikke slettes uavhengig av dem. Fristen er aapen i v1 (#424).', '143'),
    ('m52_nomenklatur', 'nomenklatur', 'konfigurasjon', 'tenant', 'registrert',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Konfigurasjon som andre rader i modulen refererer til; kan ikke slettes uavhengig av dem. Fristen er aapen i v1 (#424).', '143'),
    ('m52_varenummer', 'varenummer', 'konfigurasjon', 'tenant', 'registrert',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Konfigurasjon som andre rader i modulen refererer til; kan ikke slettes uavhengig av dem. Fristen er aapen i v1 (#424).', '143'),
    ('m52_tollvare', 'tollvare', 'driftsspor', 'tenant', 'registrert',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m52_tollforslag', 'tollforslag', 'driftsspor', 'tenant', 'klar_ts',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m52_forslagsgrunn', 'forslagsgrunn', 'driftsspor', 'tenant', 'registrert',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m52_tollfunn', 'tollfunn', 'driftsspor', 'tenant', 'forst_sett',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m47_myndighetskrav', 'myndighetskrav', 'konfigurasjon', 'tenant', 'satt_ts',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Konfigurasjon som andre rader i modulen refererer til; kan ikke slettes uavhengig av dem. Fristen er aapen i v1 (#424).', '143'),
    ('m47_regelverk', 'regelverk', 'konfigurasjon', 'tenant', 'registrert',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Konfigurasjon som andre rader i modulen refererer til; kan ikke slettes uavhengig av dem. Fristen er aapen i v1 (#424).', '143'),
    ('m47_rapportplikttype', 'rapportplikttype', 'konfigurasjon', 'tenant', 'registrert',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Konfigurasjon som andre rader i modulen refererer til; kan ikke slettes uavhengig av dem. Fristen er aapen i v1 (#424).', '143'),
    ('m47_rapportplikt', 'rapportplikt', 'driftsspor', 'tenant', 'registrert',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m47_rapportbevis', 'rapportbevis', 'persondata', 'tenant', 'registrert',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Lageret baerer opplysninger om mennesker (innsendt_av_person). Fristen er ikke bestemt i v1 — den foelger modulens egne regler der de finnes, og er ellers aapen. Navngitt her saa M-30 kan dekke det og M-4 kan maale det (#424).', '143'),
    ('m47_myndighetsfunn', 'myndighetsfunn', 'driftsspor', 'tenant', 'forst_sett',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m50_journalkrav', 'journalkrav', 'konfigurasjon', 'tenant', 'satt_ts',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Konfigurasjon som andre rader i modulen refererer til; kan ikke slettes uavhengig av dem. Fristen er aapen i v1 (#424).', '143'),
    ('m50_journalkilde', 'journalkilde', 'konfigurasjon', 'tenant', 'registrert',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Konfigurasjon som andre rader i modulen refererer til; kan ikke slettes uavhengig av dem. Fristen er aapen i v1 (#424).', '143'),
    ('m50_journalsak', 'journalsak', 'driftsspor', 'tenant', 'opprettet',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m50_journalpost', 'journalpost', 'persondata', 'tenant', 'registrert',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Lageret baerer opplysninger om mennesker (hentet_av_person). Fristen er ikke bestemt i v1 — den foelger modulens egne regler der de finnes, og er ellers aapen. Navngitt her saa M-30 kan dekke det og M-4 kan maale det (#424).', '143'),
    ('m50_journalperson', 'journalperson', 'persondata', 'tenant', 'registrert',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Lageret baerer opplysninger om mennesker (navn, rolle). Fristen er ikke bestemt i v1 — den foelger modulens egne regler der de finnes, og er ellers aapen. Navngitt her saa M-30 kan dekke det og M-4 kan maale det (#424).', '143'),
    ('m50_journalfunn', 'journalfunn', 'driftsspor', 'tenant', 'forst_sett',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m53_hmskrav', 'hmskrav', 'konfigurasjon', 'tenant', 'satt_ts',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Konfigurasjon som andre rader i modulen refererer til; kan ikke slettes uavhengig av dem. Fristen er aapen i v1 (#424).', '143'),
    ('m53_hmsregelverk', 'hmsregelverk', 'konfigurasjon', 'tenant', 'opprettet',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Konfigurasjon som andre rader i modulen refererer til; kan ikke slettes uavhengig av dem. Fristen er aapen i v1 (#424).', '143'),
    ('m53_hmsavvik', 'hmsavvik', 'driftsspor', 'tenant', 'meldt_ts',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m53_hmsmelder', 'hmsmelder', 'persondata', 'tenant', 'opprettet',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Lageret baerer opplysninger om mennesker (navn, rolle). Fristen er ikke bestemt i v1 — den foelger modulens egne regler der de finnes, og er ellers aapen. Navngitt her saa M-30 kan dekke det og M-4 kan maale det (#424).', '143'),
    ('m53_hmstiltak', 'hmstiltak', 'driftsspor', 'tenant', 'opprettet',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m53_hmsfunn', 'hmsfunn', 'driftsspor', 'tenant', 'forst_sett',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m15_likviditetskrav', 'likviditetskrav', 'konfigurasjon', 'tenant', 'satt_ts',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Konfigurasjon som andre rader i modulen refererer til; kan ikke slettes uavhengig av dem. Fristen er aapen i v1 (#424).', '143'),
    ('m15_likviditetsmodell', 'likviditetsmodell', 'konfigurasjon', 'tenant', 'opprettet',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Konfigurasjon som andre rader i modulen refererer til; kan ikke slettes uavhengig av dem. Fristen er aapen i v1 (#424).', '143'),
    ('m15_likviditetspost', 'likviditetspost', 'driftsspor', 'tenant', 'registrert',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m15_likviditetsprognose', 'likviditetsprognose', 'driftsspor', 'tenant', 'opprettet',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m15_prognosemaaling', 'prognosemaaling', 'driftsspor', 'tenant', 'maalt_ts',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m15_kostnadstiltak', 'kostnadstiltak', 'driftsspor', 'tenant', 'opprettet',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m15_likviditetsfunn', 'likviditetsfunn', 'driftsspor', 'tenant', 'forst_sett',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m33_prognosekrav', 'prognosekrav', 'konfigurasjon', 'tenant', 'satt_ts',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Konfigurasjon som andre rader i modulen refererer til; kan ikke slettes uavhengig av dem. Fristen er aapen i v1 (#424).', '143'),
    ('m33_prognosemodell', 'prognosemodell', 'konfigurasjon', 'tenant', 'opprettet',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Konfigurasjon som andre rader i modulen refererer til; kan ikke slettes uavhengig av dem. Fristen er aapen i v1 (#424).', '143'),
    ('m33_bemanningsprognose', 'bemanningsprognose', 'driftsspor', 'tenant', 'laget_ts',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m33_bemanningsmaaling', 'bemanningsmaaling', 'driftsspor', 'tenant', 'maalt_ts',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m33_prognosefunn', 'prognosefunn', 'driftsspor', 'tenant', 'forst_sett',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m36_optimaliseringskrav', 'optimaliseringskrav', 'konfigurasjon', 'tenant', 'satt_ts',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Konfigurasjon som andre rader i modulen refererer til; kan ikke slettes uavhengig av dem. Fristen er aapen i v1 (#424).', '143'),
    ('m36_optimaliseringsmodell', 'optimaliseringsmodell', 'konfigurasjon', 'tenant', 'opprettet',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Konfigurasjon som andre rader i modulen refererer til; kan ikke slettes uavhengig av dem. Fristen er aapen i v1 (#424).', '143'),
    ('m36_tiltaksforslag', 'tiltaksforslag', 'driftsspor', 'tenant', 'opprettet',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m36_portefoljestopp', 'portefoljestopp', 'driftsspor', 'tenant', 'satt_ts',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m36_rangering', 'rangering', 'driftsspor', 'tenant', 'laget_ts',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m36_effektmaaling', 'effektmaaling', 'driftsspor', 'tenant', 'maalt_ts',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m36_optimaliseringsfunn', 'optimaliseringsfunn', 'driftsspor', 'tenant', 'forst_sett',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m7_motekrav', 'motekrav', 'konfigurasjon', 'tenant', 'satt_ts',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Konfigurasjon som andre rader i modulen refererer til; kan ikke slettes uavhengig av dem. Fristen er aapen i v1 (#424).', '143'),
    ('m7_opptakshjemmel', 'opptakshjemmel', 'konfigurasjon', 'tenant', 'registrert',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Konfigurasjon som andre rader i modulen refererer til; kan ikke slettes uavhengig av dem. Fristen er aapen i v1 (#424).', '143'),
    ('m7_mote', 'mote', 'persondata', 'tenant', 'opprettet',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Lageret baerer opplysninger om mennesker (deltakere, innkalt_av). Fristen er ikke bestemt i v1 — den foelger modulens egne regler der de finnes, og er ellers aapen. Navngitt her saa M-30 kan dekke det og M-4 kan maale det (#424).', '143'),
    ('m7_moteopptak', 'moteopptak', 'persondata', 'tenant', 'registrert',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Lageret baerer opplysninger om mennesker (varslede, varslet_av). Fristen er ikke bestemt i v1 — den foelger modulens egne regler der de finnes, og er ellers aapen. Navngitt her saa M-30 kan dekke det og M-4 kan maale det (#424).', '143'),
    ('m7_referatpunkt', 'referatpunkt', 'driftsspor', 'tenant', 'registrert',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m7_motebeslutning', 'motebeslutning', 'persondata', 'tenant', 'registrert',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Lageret baerer opplysninger om mennesker (besluttet_av). Fristen er ikke bestemt i v1 — den foelger modulens egne regler der de finnes, og er ellers aapen. Navngitt her saa M-30 kan dekke det og M-4 kan maale det (#424).', '143'),
    ('m7_moteaksjon', 'moteaksjon', 'driftsspor', 'tenant', 'opprettet',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m7_motefunn', 'motefunn', 'driftsspor', 'tenant', 'forst_sett',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m20_innholdskrav', 'innholdskrav', 'konfigurasjon', 'tenant', 'satt',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Konfigurasjon som andre rader i modulen refererer til; kan ikke slettes uavhengig av dem. Fristen er aapen i v1 (#424).', '143'),
    ('m20_innholdsutkast', 'innholdsutkast', 'driftsspor', 'tenant', 'opprettet',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m20_innholdspaastand', 'innholdspaastand', 'driftsspor', 'tenant', 'registrert',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m20_innholdsvisning', 'innholdsvisning', 'persondata', 'tenant', 'vist_ts',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Lageret baerer opplysninger om mennesker (vist_for). Fristen er ikke bestemt i v1 — den foelger modulens egne regler der de finnes, og er ellers aapen. Navngitt her saa M-30 kan dekke det og M-4 kan maale det (#424).', '143'),
    ('m20_innholdspublisering', 'innholdspublisering', 'persondata', 'tenant', 'publisert_ts',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Lageret baerer opplysninger om mennesker (publisert_av, tilbake_av). Fristen er ikke bestemt i v1 — den foelger modulens egne regler der de finnes, og er ellers aapen. Navngitt her saa M-30 kan dekke det og M-4 kan maale det (#424).', '143'),
    ('m20_innholdsfunn', 'innholdsfunn', 'driftsspor', 'tenant', 'forst_sett',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m43_telefonikrav', 'telefonikrav', 'konfigurasjon', 'tenant', 'satt',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Konfigurasjon som andre rader i modulen refererer til; kan ikke slettes uavhengig av dem. Fristen er aapen i v1 (#424).', '143'),
    ('m43_eskaleringsregel', 'eskaleringsregel', 'konfigurasjon', 'tenant', 'registrert',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Konfigurasjon som andre rader i modulen refererer til; kan ikke slettes uavhengig av dem. Fristen er aapen i v1 (#424).', '143'),
    ('m43_samtale', 'samtale', 'persondata', 'tenant', 'registrert',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Lageret baerer opplysninger om mennesker (motpart). Fristen er ikke bestemt i v1 — den foelger modulens egne regler der de finnes, og er ellers aapen. Navngitt her saa M-30 kan dekke det og M-4 kan maale det (#424).', '143'),
    ('m43_samtaleopptak', 'samtaleopptak', 'persondata', 'tenant', 'registrert',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Lageret baerer opplysninger om mennesker (varslede, varslet_av). Fristen er ikke bestemt i v1 — den foelger modulens egne regler der de finnes, og er ellers aapen. Navngitt her saa M-30 kan dekke det og M-4 kan maale det (#424).', '143'),
    ('m43_transkripsjonslinje', 'transkripsjonslinje', 'driftsspor', 'tenant', 'registrert',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m43_eskalering', 'eskalering', 'driftsspor', 'tenant', 'eskalert_ts',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m43_telefonifunn', 'telefonifunn', 'driftsspor', 'tenant', 'forst_sett',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m45_esgkrav', 'esgkrav', 'konfigurasjon', 'tenant', 'satt',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Konfigurasjon som andre rader i modulen refererer til; kan ikke slettes uavhengig av dem. Fristen er aapen i v1 (#424).', '143'),
    ('m45_rapportperiode', 'rapportperiode', 'driftsspor', 'tenant', 'opprettet',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m45_utslippsfaktor', 'utslippsfaktor', 'driftsspor', 'tenant', 'registrert',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m45_esgmaaling', 'esgmaaling', 'driftsspor', 'tenant', 'registrert',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m45_esgpaastand', 'esgpaastand', 'driftsspor', 'tenant', 'registrert',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m45_esgrapport', 'esgrapport', 'driftsspor', 'tenant', 'sammenstilt',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143'),
    ('m45_esgfunn', 'esgfunn', 'driftsspor', 'tenant', 'forst_sett',
     NULL, NULL, NULL, NULL, 'uten_frist_apen',
     'Driftsspor: funn, hendelser og maalinger modulen selv skrev. Fristen er ikke bestemt i v1; navngitt saa M-4 kan maale det (#424).', '143')
ON CONFLICT (lager_id) DO NOTHING;
RESET ROLE;
